server:
  port: 8083

default:
  bake:
    account: default

clouddriver:
  baseUrl: http://localhost:7002
front50:
  baseUrl: http://localhost:8080
oort:
  baseUrl: ${clouddriver.baseUrl}
mort:
  baseUrl: ${clouddriver.baseUrl}
kato:
  baseUrl: ${clouddriver.baseUrl}
echo:
  enabled: false
igor:
  baseUrl: http://localhost:8088
bakery:
  baseUrl: http://localhost:8089
  # Rosco exposes more endpoints than Netflix's internal bakery. This disables
  # the use of those endpoints.
  roscoApisEnabled: true
  allowMissingPackageInstallation: false

redis:
  connection: ${REDIS_URL:redis://localhost:6379}

tasks:
  useWaitForAllNetflixAWSInstancesDownTask: false

